Optional function for new context building
graph-gophers/graphql-transport-ws pull request #27
Opened 2020-08-20 02:52 UTC by cschofieldffx

Added optional functions to the NewHandlerFunc that let you pull values from the http.Request context and build up a new context that will be supplied to the go routine.

2020-08-20 03:02 UTC, dackroyd requested changes

2020-08-20 03:02 UTC, dackroyd commented on graphqlws/http.go
> +						return
`err` here is completely discarded without indicating any failure to the response? Seems the other error cases unfortunately do the same... I'd expect HTTP error to be returned, though I'd need to refer back to the `graphql-ws` spec to check what behaviour is intended

2020-08-20 03:02 UTC, dackroyd commented on graphqlws/http.go
> +				var err error
var for `err` here likely not needed if scope of the context building error is limited to within the loop?

2020-08-20 03:02 UTC, dackroyd commented on graphqlws/http.go
> +type ContextBuilderFunc func(ctx context.Context, r *http.Request) (context.Context, error)
Consider support for builders that aren't functions, similar to `http.Handler` / `http.HandlerFunc` ?

2020-08-20 03:02 UTC, dackroyd commented on graphqlws/http.go
> +type ContextBuilderFunc func(ctx context.Context, r *http.Request) (context.Context, error)
Doc comments for the exported types and functions are needed

2020-08-20 03:02 UTC, dackroyd commented on graphqlws/http.go
> +
Nit: unrelated

2020-08-20 03:22 UTC, cschofieldffx commented on graphqlws/http.go
> +				var err error
if i defined err like ctx, err := b(ctx, r) I get a var ctx not used error

2020-08-20 03:22 UTC, cschofieldffx commented on graphqlws/http.go
> +						return
As this runs prior to the upgrade & WS connection being created I'd assume we can respond with a HTTP error

2020-08-21 01:04 UTC, cschofieldffx commented on graphqlws/http.go
> +				var err error
Oh i misunderstood this feedback.

2020-08-26 07:35 UTC, dackroyd requested changes

2020-08-26 07:35 UTC, dackroyd commented on graphqlws/http.go
> +type Handler interface {
Naming: `Handler`

This _builds a context_, rather than 'handling' anything. `Handler` also may cause some confusion with `http.Handler`

2020-08-26 07:35 UTC, dackroyd commented on graphqlws/http.go
> +func NewHandlerFunc(svc connection.GraphQLService, httpHandler http.Handler, wsHandler ...Handler) http.HandlerFunc {
`, wsHandler ...Handler` means this can only support these handlers (optionally), but we won't be able to add any _other_ optional parameter types in the future, limiting the extensibility of `NewHandlerFunc`

2020-08-26 07:35 UTC, dackroyd commented on graphqlws/internal/connection/connection.go
> +func Connect(ctx context.Context, ws wsConnection, service GraphQLService, options ...func(conn *connection)) func() {
This change should require the unit test to be updated?

2020-08-26 07:35 UTC, dackroyd commented on graphqlws/http.go
> +type HandlerFunc func(context.Context, *http.Request) (context.Context, error)
Need unit tests which verify behaviour of the handler with (and without) extra context builder(s)?

2020-08-26 07:35 UTC, dackroyd commented on graphqlws/http.go
> +type HandlerFunc func(context.Context, *http.Request) (context.Context, error)
Nit: worth documenting that the request should not be modified, and _why_ it is supplied?

2020-08-26 07:35 UTC, dackroyd commented on graphqlws/http.go
> +// The HandlerFunc type is an adapter to allow the use
Incorrect docs?

2020-08-31 10:23 UTC, dackroyd requested changes
Nearly there 👌

2020-08-31 10:23 UTC, dackroyd commented on graphqlws/http.go
> +	o := applyOptions(options...)
Looking at the diff, I’ve realised that `applyOptions` should probably be applied _once only_, not per-request (typical case for functional options with closures)? Building the context obviously still needs to be done per-request

2020-08-31 10:23 UTC, dackroyd commented on graphqlws/http_test.go
> +			Want: want{Context: context.Background(), Error: nil},
`nil` is the default value for `Error`, can/should be omitted

2020-08-31 10:23 UTC, dackroyd commented on graphqlws/http_test.go
> +		"With_context_generators": {
No tests cover an error being returned by the context generator?

2020-08-31 10:23 UTC, dackroyd commented on graphqlws/http_test.go
> +				assert.EqualError(t, tt.Want.Error, err.Error(), "Expected error")
In the case of `EqualError`, the actual error should be the second argument (`t` being the first), and the _expected message string_ should be the third?

In that case, the test would setup the wanted error `string` rather than `error`

2020-09-03 00:22 UTC, cschofieldffx commented
@pavelnikolov If all @dackroyd's concerns are addressed are we able to get this change merged?

2020-09-03 03:42 UTC, dackroyd commented on graphqlws/http_test.go
> +				return
An error here should fail the test? This is a precondition, so:

```
req, err := http.NewRequest("GET", "/graphql", nil)
require.NoError(t, err, "Failed to create request")
```

2020-09-04 06:51 UTC, pavelnikolov approved these changes

2020-09-04 06:51 UTC, merged